### ISSUE TITLE
Invalid transport configuration 

### ISSUE THREAD

**Issue by Ramsar** [MicrosoftDocs/mslearn-your-first-iot-central-app#5]
After following the steps in the tutorial and trying to run the app I get the following 'Invalid transport configuration' error. 

PS C:\Users\kw1\RefrigeratedTruck> node app.js
Starting Truck number 1
C:\Users\kw1\node_modules\azure-iot-mqtt-base\lib\mqtt_base.js:227
            throw new ReferenceError('Invalid transport configuration');
            ^

ReferenceError: Invalid transport configuration
    at MqttBase.connect (C:\Users\kw1\node_modules\azure-iot-mqtt-base\lib\mqtt_base.js:227:19)
    at C:\Users\kw1\node_modules\azure-iot-device-mqtt\lib\mqtt.js:227:49
    at C:\Users\kw1\node_modules\azure-iot-device-mqtt\lib\mqtt.js:979:17
    at C:\Users\kw1\node_modules\azure-iot-device\lib\utils.js:39:13
    at Object.getAgentPlatformString (C:\Users\kw1\node_modules\azure-iot-common\lib\utils.js:39:9)
    at C:\Users\kw1\node_modules\azure-iot-device\lib\utils.js:37:28
    at Object.noErrorCallbackToPromise (C:\Users\kw1\node_modules\azure-iot-common\lib\promise_utils.js:59:16)
    at Object.getUserAgentString (C:\Users\kw1\node_modules\azure-iot-device\lib\utils.js:35:31)
    at Mqtt._ensureAgentString (C:\Users\kw1\node_modules\azure-iot-device-mqtt\lib\mqtt.js:977:32)
    at C:\Users\kw1\node_modules\azure-iot-device-mqtt\lib\mqtt.js:225:39

**Comment by Ramsar** [comment]
Solved, was using a wrong connection string
